services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - tasks_db:/app/tasks.db
      
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  tasks_db: {}
