"""add
Revision ID: 6891389f580a
Revises: 3ce1000eb355
Create Date: 2026-06-18 17:18:52.529116
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6891389f580a'
down_revision = '3ce1000eb355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
